services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel
      POSTGRES_DB: sentinel
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Expose sur le 3001 (Grafana est sur le 3000)
    volumes:
      - ./backend:/app
      - /app/node_modules # Évite d'écraser les modules Linux avec ceux de votre machine
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway" # Permet de joindre le Mosquitto de l'hôte
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  db_data: